name: LGSCV
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  - plyfile=0.8.1
  - python=3.9.18
  - pip=22.3.1
  - pytorch=1.13.0
  - torchaudio=0.13.0
  - torchvision=0.14.0
  - tqdm
  - icecream
  - pandas
  - natsort
  - kornia
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - submodules/fused-ssim
    - git+https://github.com/fraunhoferhhi/PLAS.git
    - opencv-python
    - lpips
    - trimesh